services:
  redis:
    image: redis:latest
    container_name: labseq-redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: labseq-backend
    environment:
      - QUARKUS_REDIS_HOSTS=redis://redis:6379
    ports:
      - "8080:8080"
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: labseq-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
